"""
Layer 05 · Alerts — Gmail SMTP Email Alerts
Fallback / supplement to Telegram for daily summaries.
"""
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, List

from config.settings import ALERT_EMAIL_TO, GMAIL_APP_PASSWORD, GMAIL_USER

logger = logging.getLogger(__name__)


def _send_email(subject: str, body_html: str) -> bool:
    if not GMAIL_USER or not GMAIL_APP_PASSWORD or not ALERT_EMAIL_TO:
        logger.debug("Email not configured — skipping")
        return False
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = GMAIL_USER
        msg["To"] = ALERT_EMAIL_TO
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, ALERT_EMAIL_TO, msg.as_string())
        logger.info("Email sent: %s", subject)
        return True
    except Exception as e:
        logger.warning("Email send failed: %s", e)
        return False


def _signal_row(s: Dict) -> str:
    return (
        f"<tr>"
        f"<td><b>{s['ticker']}</b></td>"
        f"<td>{s['composite_score']:.1f}</td>"
        f"<td>${s.get('entry_price', 0):.3f}</td>"
        f"<td>${s.get('target_price', 0):.3f}</td>"
        f"<td>${s.get('stop_loss_price', 0):.3f}</td>"
        f"<td>${s.get('position_size_aud', 0):,.0f}</td>"
        f"</tr>"
    )


def send_daily_email(signals: List[Dict], watchlist_summary: Dict, regime: Dict) -> bool:
    from datetime import date
    today = date.today().strftime("%d %b %Y")
    regime_str = "RISK-ON ✅" if regime.get("regime_ok") else "RISK-OFF ⚠️"
    xjo = regime.get("xjo", "N/A")
    ema200 = regime.get("ema200", "N/A")
    pnl = watchlist_summary.get("total_unrealised_pnl", 0)
    positions = watchlist_summary.get("total_positions", 0)

    rows = "\n".join(_signal_row(s) for s in signals[:10])

    html = f"""
<html><body style="font-family:Arial,sans-serif;color:#333;">
<h2>ASX AI Trading — Daily Report {today}</h2>

<h3>Market Regime: {regime_str}</h3>
<p>XJO: <b>{xjo}</b> | EMA-200: <b>{ema200}</b></p>

<h3>Portfolio: {positions} Active Positions | Unrealised P&L: <b>${pnl:+,.2f}</b></h3>

<h3>Top Signals Today</h3>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
<tr style="background:#f0f0f0;">
  <th>Ticker</th><th>Score</th><th>Entry</th><th>Target</th><th>Stop</th><th>Position</th>
</tr>
{rows}
</table>

<p style="color:#888;font-size:12px;">Generated by ASX AI Trading System</p>
</body></html>
"""
    return _send_email(f"ASX AI Trading — Daily Report {today}", html)
