# NIFTY 100 constituent tickers (NIFTY 50 + NIFTY Next 50) — NSE suffix .NS
NIFTY100_TICKERS = [
    # ── NIFTY 50 ──────────────────────────────────────────────────────────────
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS",
    "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS",
    "BPCL.NS", "BHARTIARTL.NS", "BRITANNIA.NS", "CIPLA.NS",
    "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS",
    "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS",
    "ICICIPRULI.NS", "INDUSINDBK.NS", "INFY.NS", "ITC.NS",
    "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS", "M&M.NS",
    "MARUTI.NS", "NESTLEIND.NS", "NTPC.NS", "ONGC.NS",
    "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SBIN.NS",
    "SHREECEM.NS", "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "TCS.NS", "TECHM.NS", "TITAN.NS",
    "ULTRACEMCO.NS", "WIPRO.NS",
    # ── NIFTY Next 50 ─────────────────────────────────────────────────────────
    "ABB.NS", "ADANIGREEN.NS", "AMBUJACEM.NS", "ATGL.NS",
    "BANKBARODA.NS", "BERGEPAINT.NS", "BOSCHLTD.NS", "CANBK.NS",
    "CGPOWER.NS", "CHOLAFIN.NS", "COLPAL.NS", "CUMMINSIND.NS",
    "DLF.NS", "DMART.NS", "GODREJCP.NS", "GUJGASLTD.NS",
    "HAL.NS", "HAVELLS.NS", "IDFCFIRSTB.NS", "INDIGO.NS",
    "IRCTC.NS", "IRFC.NS", "JSWENERGY.NS", "LICI.NS",
    "LUPIN.NS", "MANKIND.NS", "MARICO.NS", "UNITDSPR.NS",
    "MOTHERSON.NS", "MUTHOOTFIN.NS", "NHPC.NS", "NMDC.NS",
    "NYKAA.NS", "OFSS.NS", "PAGEIND.NS", "PFC.NS",
    "PIIND.NS", "PIDILITIND.NS", "PNB.NS", "RECLTD.NS",
    "SAIL.NS", "SIEMENS.NS", "SRF.NS", "TATAPOWER.NS",
    "TATAMOTORS.NS", "TRENT.NS", "UPL.NS", "VBL.NS",
    "VEDL.NS", "ZOMATO.NS",
]

# Bare NSE symbols (no .NS suffix) for announcement scraping
NIFTY100_CODES = [t.replace(".NS", "") for t in NIFTY100_TICKERS]
